version: "3.7"

services:
  # for development
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    container_name: node_app
    ports:
      - "33000:3000"
      # for debugger
      - "9229:9229"
      # for prisma
      - "5555:5555"
    # to avoid "PID 1" problem
    init: true
    volumes:
      - "./app:/home/node/app"
    env_file:
      - .env.local
    tty: true
    # command: npm run start:dev

  # for CI testing
  ci-test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: test
    container_name: node_ci_test
    ports:
      - "44000:3000"
    # to avoid "PID 1" problem
    init: true
    volumes:
      - ./app:/home/node/app
      # to avoid overwrote and cleared by host machine
      - node_modules:/home/node/app/node_modules
    env_file:
      - .env.local
    # command: npm run ci:test

volumes:
  node_modules:
